[package]
name = "deserialize_tilde"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
indexmap = "2.2.6"
rayon = "1.10.0"
serde = { version = "1.0.204", features = ["derive"] }
split-iter = "0.1.0"
unicode-segmentation = "1.11.0"
